# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "The Dexome blog"
license = "MIT"
licenselink = "https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "The notes from my experiments"
homepage = "https://blog.dexome.com"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"
theme = "ananke"

[author]
  name = "dexter"
  homepage = "https://blog.dexome.com/"

title = "The Dexome blog"
baseURL = "https://blog.dexome.com"
languageCode = "en-us"
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Dexome blog"
    weight = 1
    contentDir = "content/en"
#   [languages.fr]
#     title = "Mon blogue"
#     weight = 2
#     contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/Dexome-2-cutout.png"
  description = "The notes from my experiments"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
#   featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = ""
  recent_posts_number = 2

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
